### ISSUE TITLE
Retour 6 

### ISSUE THREAD

**Issue by JbIPS** [JbIPS/landing-stan#1]
- [x] Etat actif sur la pastille du menu (@Fluoflo peux-tu nous donner la couleur ?)
- [x] Enlever la languette du formulaire de contact en XL

**Comment by Fluoflo** [comment]
Pour l'état actif du menu je recommande les couleurs suivantes : pastille jaune, rectangle bleu, écriture blanche.
Au passage, les titres "Pourquoi..." et "A propos" sont plus petits que les autres, peux-tu les mettre à la même taille stp.
